# Generated by Django 4.1.7 on 2023-04-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.CharField(default='2023-01-01', max_length=50)),
                ('event_time', models.CharField(default='12:00', max_length=50)),
                ('reminder_date', models.CharField(default='2023-01-01', max_length=50)),
                ('reminder_time', models.CharField(default='12:00', max_length=50)),
            ],
        ),
    ]
