# Generated by Django 4.1.7 on 2023-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(default='Guest', max_length=50),
        ),
    ]
