# Generated by Django 4.1.7 on 2023-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboardapp', '0002_notice_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='Notice', max_length=50),
        ),
    ]
