# Generated by Django 4.1.7 on 2023-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboardapp', '0003_notice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.CharField(default='Guest', max_length=50),
        ),
    ]
